name: React CI/CD Pipeline

# This triggers the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # This specifies the OS for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up the Node.js environment
        with:
          node-version: '16'  # Specifies the version of Node.js

      - name: Install dependencies
        run: npm install  # Installs the required dependencies

      - name: Build the app
        run: npm run build  # Builds the React app for production

  tests:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js 18.x to run Test
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        run: npm run test

      #- name: Build the app
      #  run: npm run build  # Builds the React app for production
  # Job to deploy the application after build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests  # Ensures the deploy job runs only after the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Re-checks out the code for deployment

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Pulls Vercel token from GitHub secrets
        run: npx vercel --prod --yes --token $VERCEL_TOKEN 
        #run: npx vercel --prod  # Runs the Vercel deployment in production mode
        #env:
        #  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Uses the Vercel token from GitHub Secrets
